image: gradle:jdk16

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

variables:
  GIT_STRATEGY: clone

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
  key: "$CI_BUILD_REF_NAME"

build:
  stage: build
  script:
    - gradle screamCompile test