name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.job }}-${{ matrix.java }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and publish with Gradle
        run: ./gradlew -Prelease.useLastTag=true -Prelease final screamCompile
        env:
          OPTIMIZE_FOR_CI_CD: 1
          NEXUS_URL_RELEASE: https://repo.hoznet.dev/releases
          NEXUS_URL_SNAPSHOT: https://repo.hoznet.dev/snapshots
          NEXUS_USERNAME: github
          NEXUS_PASSWORD: ${{ secrets.REPOSILITE_CI_TOKEN }}
